# MongoDB Configuration
mongodb:
  uri: "mongodb://localhost:27017/"
  database: "emotion_chatbot"
  collection: "chat_logs"

# LLM Configuration
llm:
  model_name: "gemma:2b"
  # Alternative models
  # model_name: "gemma:2b"
  #model_name: "deepseek-r1:latest"

ollama:
  api_url: "http://127.0.0.1:11434/api"

# Speech Processing Configuration
speech:
  # Text-to-Speech (TTS)
  tts:
    # TTS engine options
    
    text_processing:
      remove_chars: ["'", "\"", "`", "#", "@", "*"]  # Characters to always remove
      keep_chars: [".", ",", "!", "?", ";", ":", "-"]  # Punctuation to preserve
      max_punctuation: 2  # Max consecutive punctuation marks to allow
    voice_preferences:
      english_female: "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech\\Voices\\Tokens\\TTS_MS_EN-US_ZIRA_11.0"
      english_male: "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech\\Voices\\Tokens\\TTS_MS_EN-US_DAVID_11.0"
    engine: "pyttsx3"  # Options: "pyttsx3", "StyleTTS2", "Whisper Turbo"
    output_path: "./outputs/speech/"
    
    # Core voice settings
    base_rate: 190      # Normal speech rate (words per minute)
    base_volume: 1.0    # Volume (0.0 to 1.0)
    default_gender: "female"  # Default voice gender
    
    # Human-like speech parameters
    human_like:
      enabled: true
      # Pause durations in seconds (base values)
      pause_durations:
        comma: 0.2
        period: 0.3
        question: 0.5
        exclamation: 0.4
      variation_range: 0.2    # +/- range for random variation (0.0-1.0)
      emphasis:
        probability: 0.6      # Chance to emphasize important words
        min_word_length: 5    # Minimum word length to consider
        level: "moderate"     # Emphasis level: "weak", "moderate", "strong"
    
    # Voice profiles for different roles
    voice_profiles:
      default:
        gender: "female"
        rate_modifier: 1.0
        pitch_modifier: 1.0
      call_center:
        gender: "female"
        rate_modifier: 1.1
        pitch_modifier: 1.05
      tech_support:
        gender: "male"
        rate_modifier: 0.95
        pitch_modifier: 0.9
      emotional:
        gender: "female"
        rate_modifier: 1.0
        pitch_modifier: 1.1
    
    # Conversation state adjustments
    state_adjustments:
      rate_modifiers:
        neutral: 1.0
        question: 0.9
        emphasis: 0.85
        explaining: 0.8
        excited: 1.2
      volume_modifiers:
        neutral: 1.0
        emphasis: 1.2
        question: 1.1
        explaining: 1.0
        excited: 1.15
  
  # Speech-to-Text (STT)
  stt:
    engine: "vosk"  # Options: "vosk", "whisper-local"
    model_path: "./models/vosk/"  # Path to Vosk models

# Personality Configuration
personality:
  default: "default"
  
# Language Configuration
language:
  default: "english"  # Default language
  supported: ["urdu", "english", "hindi", "punjabi"]  # Supported languages
  # Model paths for different languages (for Vosk STT)
  models:
    urdu: "vosk-model-small-hi-0.22"
    english: "vosk-model-small-en-us-0.15"
    hindi: "vosk-model-small-hi-0.22"
    punjabi: "vosk-model-smalls-hi-0.22"
    indian_english: "vosk-model-small-en-in-0.4"

# Reinforcement Learning Configuration
rl:
  learning_rate: 0.001
  gamma: 0.95
  epsilon: 0.2
  enabled: true
  rewards:
    transitions:
      neutral_to_neutral: 0.1
      neutral_to_happy: 0.7
      neutral_to_sad: -0.3
      neutral_to_angry: -0.5
      happy_to_happy: 0.5
      happy_to_neutral: 0.0
      happy_to_sad: -0.7
      happy_to_angry: -0.8
      sad_to_happy: 0.8
      sad_to_neutral: 0.5
      sad_to_sad: -0.2
      sad_to_angry: -0.5
      angry_to_happy: 0.9
      angry_to_neutral: 0.7
      angry_to_sad: -0.1
      angry_to_angry: -0.6

# Data Configuration
data:
  raw_data_path: "data/RU-EN-Emotion Dataset.xlsx"
  processed_data_path: "./data/processed/"